CREATE TABLE AGE_LIMIT_TYPES
(
AGE_LIMIT_ID INTEGER NOT NULL ,
AGE_LIMIT_VALUE INTEGER NOT NULL
);

ALTER TABLE AGE_LIMIT_TYPES
ADD CONSTRAINT XPKAGE_LIMIT_TYPES PRIMARY KEY (AGE_LIMIT_ID);

CREATE TABLE FILM_TYPES
(
FILM_TYPE_ID INTEGER NOT NULL ,
FILM_TYPE_NAME VARCHAR2(20) NULL
);

ALTER TABLE FILM_TYPES
ADD CONSTRAINT XPKSEANCE_TYPES PRIMARY KEY (FILM_TYPE_ID);

CREATE TABLE FILMS
(
FILM_ID INTEGER NOT NULL ,
FILM_NAME VARCHAR2(20) NOT NULL ,
FILM_TYPE_ID INTEGER NULL ,
AGE_LIMIT_ID INTEGER NULL
);

ALTER TABLE FILMS
ADD CONSTRAINT XPKFILMS PRIMARY KEY (FILM_ID);

CREATE TABLE LINES
(
LINE_NUMBER INTEGER NOT NULL ,
LINE_ID INTEGER NOT NULL ,
THEATER_ID INTEGER NULL
);

ALTER TABLE LINES
ADD CONSTRAINT XPKLINES PRIMARY KEY (LINE_ID);

CREATE TABLE SEANCES
(
SEANCE_ID INTEGER NOT NULL ,
FILM_ID INTEGER NOT NULL ,
BASE_PRICE_VALUE INTEGER NOT NULL ,
SEANCE_START_DATE DATE NOT NULL
);

ALTER TABLE SEANCES
ADD CONSTRAINT XPKSEANCES PRIMARY KEY (SEANCE_ID);

CREATE TABLE SEAT_TYPES
(
SEAT_TYPE_ID INTEGER NOT NULL ,
SEAT_TYPE_NAME VARCHAR2(20) NOT NULL
);

ALTER TABLE SEAT_TYPES
ADD CONSTRAINT XPKSEAT_TYPES PRIMARY KEY (SEAT_TYPE_ID);

CREATE TABLE SEATS
(
SEAT_NUMBER INTEGER NOT NULL ,
SEAT_TYPE_ID INTEGER NULL ,
LINE_ID INTEGER NULL ,
SEAT_ID INTEGER NOT NULL
);

ALTER TABLE SEATS
ADD CONSTRAINT XPKSEAT PRIMARY KEY (SEAT_ID);

CREATE TABLE SEATS_SEANCES_STATUSES
(
STATUS_ID INTEGER NOT NULL ,
STATUS_NAME VARCHAR2(20) NULL
);

ALTER TABLE SEATS_SEANCES_STATUSES
ADD CONSTRAINT XPKSEATS_SEANCES_STATUSES PRIMARY KEY (STATUS_ID);

CREATE TABLE SEATS_SEANCES
(
SEAT_ID INTEGER NULL ,
SEANCE_ID INTEGER NULL ,
STATUS_ID INTEGER NULL ,
BOOK_KEY VARCHAR2(20) NULL
);

CREATE TABLE THEATER
(
THEATER_ID INTEGER NOT NULL ,
THEATER_NUMBER INTEGER NULL
);

ALTER TABLE THEATER
ADD CONSTRAINT XPKTHEATER PRIMARY KEY (THEATER_ID);

CREATE TABLE USER_ROLES
(
ROLE_ID INTEGER NOT NULL ,
ROLE_NAME VARCHAR2(20) NULL
);

ALTER TABLE USER_ROLES
ADD CONSTRAINT XPKUSER_ROLES PRIMARY KEY (ROLE_ID);

CREATE TABLE USERS
(
USER_ID INTEGER NOT NULL ,
LOGIN VARCHAR2(20) NOT NULL ,
PASSWORD VARCHAR2(20) NOT NULL ,
ROLE_ID INTEGER NOT NULL
);

ALTER TABLE USERS
ADD CONSTRAINT XPKUSERS PRIMARY KEY (USER_ID);

ALTER TABLE FILMS
ADD (CONSTRAINT R_11 FOREIGN KEY (FILM_TYPE_ID) REFERENCES FILM_TYPES (FILM_TYPE_ID) ON DELETE SET NULL);

ALTER TABLE FILMS
ADD (CONSTRAINT R_12 FOREIGN KEY (AGE_LIMIT_ID) REFERENCES AGE_LIMIT_TYPES (AGE_LIMIT_ID) ON DELETE SET NULL);

ALTER TABLE LINES
ADD (CONSTRAINT R_10 FOREIGN KEY (THEATER_ID) REFERENCES THEATER (THEATER_ID) ON DELETE SET NULL);

ALTER TABLE SEANCES
ADD (CONSTRAINT R_13 FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID) ON DELETE SET NULL);

ALTER TABLE SEATS
ADD (CONSTRAINT R_1 FOREIGN KEY (SEAT_TYPE_ID) REFERENCES SEAT_TYPES (SEAT_TYPE_ID) ON DELETE SET NULL);

ALTER TABLE SEATS
ADD (CONSTRAINT R_4 FOREIGN KEY (LINE_ID) REFERENCES LINES (LINE_ID) ON DELETE SET NULL);

ALTER TABLE SEATS_SEANCES
ADD (CONSTRAINT R_6 FOREIGN KEY (SEAT_ID) REFERENCES SEATS (SEAT_ID) ON DELETE SET NULL);

ALTER TABLE SEATS_SEANCES
ADD (CONSTRAINT R_7 FOREIGN KEY (SEANCE_ID) REFERENCES SEANCES (SEANCE_ID) ON DELETE SET NULL);

ALTER TABLE SEATS_SEANCES
ADD (CONSTRAINT R_8 FOREIGN KEY (STATUS_ID) REFERENCES SEATS_SEANCES_STATUSES (STATUS_ID) ON DELETE SET NULL);

ALTER TABLE USERS
ADD (CONSTRAINT R_14 FOREIGN KEY (ROLE_ID) REFERENCES USER_ROLES (ROLE_ID) ON DELETE SET NULL);